theme = "my-default"

[editor]
auto-save = true
bufferline = "always"
color-modes = true
completion-replace = true
completion-timeout = 5
completion-trigger-len = 1
cursorline = true
line-number = "relative"
shell = ["zsh", "-c"]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control", "spacer", "diagnostics"]
center = ["file-base-name", "file-modification-indicator"]
right = [
  "primary-selection-length",
  "separator",
  "position",
  "separator",
  "spacer",
  "file-line-ending",
  "spacer",
  "separator",
  "spacer",
  "file-type",
  "spacer",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
C-c = "increment"
C-f = ":fmt"
C-r = "redo"
C-w = ":w"

[keys.normal.space]
q = ":wqa"
x = ":bc"
W = ":w"
e = [":w", ":sh cargo run -q --color=always &> rifo"]

[keys.normal.space.";"]
f = ":fmt"
o = ":config-open"
r = [":w", ":config-reload"]
t = ":open ~/.config/helix/themes/my-default.toml"
